name: Azure Static Web App Deploy

on:
  workflow_run:
    workflows: ["Run Tests and Upload Coverage"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_MEADOW_0FBB07C03 }}
          action: "upload"
          app_location: "./client"
          api_location: ""
          app_artifact_location: "dist"
