name: Deploy Static Web App (after tests)

on:
  workflow_run:
    workflows: ["Run Tests and Upload Coverage"]
    types: [completed]

jobs:
  build_and_deploy:
    if: github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch   == 'main'
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout commit that passed tests
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & build React client
        working-directory: client
        run: |
          npm ci
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_MEADOW_0FBB07C03 }}
          action: upload
          app_location: "client"
          api_location: ""
          app_artifact_location: "dist"
