name: Build and deploy Node.js app to Azure Web App - artisan-api-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies & run optional build/test
        working-directory: server
        run: |
          npm install
          npm run build --if-present
          npm run test || echo "No tests configured"

      - name: Zip build output
        run: |
          cd server
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FB1CA889DE85455583939A63BFF9F99D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_61C4FC8C9092412CAA937BB2FA450238 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_50413D9C13914ED49FC8B6DC584A696E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "artisan-api-server"
          slot-name: "Production"
          package: .
