# .github/workflows/ci-cd-pipeline.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run client tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Run tests with coverage
        working-directory: ./client
        run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: uno791/local-artisan-marketplace
          directory: ./client/coverage

  deploy_static:
    name: Build & deploy static site
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install OIDC client
        run: npm install @actions/core@1.6.0 @actions/http-client

      - name: Get GitHub ID token
        id: idtoken
        uses: actions/github-script@v6
        with:
          script: |
            const coredemo = require('@actions/core')
            return await coredemo.getIDToken()
          result-encoding: string

      - name: Build & deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_MEADOW_0FBB07C03 }}
          action: upload
          app_location: ./client
          api_location: ""
          app_artifact_location: dist
          github_id_token: ${{ steps.idtoken.outputs.result }}

  deploy_server:
    name: Build & deploy API server
    needs: deploy_static
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install & build server
        working-directory: ./server
        run: |
          npm install
          npm run build --if-present

      - name: Zip server artifact
        run: |
          cd server
          zip -r ../release.zip .

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_334AA9FF7E8E4FB9BC043DDC768BB897 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C5B9662CFB964D0186E0D4BCF83307AB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_674A6760FA0C4B3D849AA2215344EE0A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: artisan-api-server1
          slot-name: Production
          package: release.zip
