name: Build and deploy Node.js app to Azure Web App - artisan-api-server1

on:
  workflow_run:
    workflows: ["Run Tests and Upload Coverage"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Zip release
        run: zip -r release.zip .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: node-app
          path: release.zip

  deploy:
    needs: build
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3.1.4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2.2.10
        with:
          app-name: "artisan-api-server1"
          slot-name: "production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
