name: Deploy API App Service (after tests)

on:
  workflow_run:
    workflows: ["Run Tests and Upload Coverage"]
    types: [completed]

jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch   == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout commit that passed tests
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install & build server
        working-directory: server
        run: |
          npm ci
          npm run build         # remove if you have no build step
          zip -r ../server.zip .

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: api-release
          path: server.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artefact
        uses: actions/download-artifact@v4
        with:
          name: api-release

      - name: Unzip artefact
        run: unzip server.zip

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_334AA9FF7E8E4FB9BC043DDC768BB897 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C5B9662CFB964D0186E0D4BCF83307AB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_674A6760FA0C4B3D849AA2215344EE0A }}

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: "artisan-api-server1"
          slot-name: "Production"
          package: .
