name: Build and deploy Node.js app to Azure Web App - artisan-api-server1

on:
  workflow_run:
    workflows:
      - "Azure Static Web Apps CI/CD"
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install dependencies & run optional build/test
        working-directory: server
        run: |
          npm install
          npm run build --if-present
          npm run test || echo "No tests configured"

      - name: Zip build output
        run: |
          cd server
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_334AA9FF7E8E4FB9BC043DDC768BB897 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C5B9662CFB964D0186E0D4BCF83307AB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_674A6760FA0C4B3D849AA2215344EE0A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: artisan-api-server1
          slot-name: Production
          package: .
